services:
  frontend:
    container_name: nextunesolutions-frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/src
    command: yarn dev
    environment:
      API_BASE_URL: $API_BASE_URL
    ports:
      - "3000:3000"
