// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/28/2025, 10:55:32 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/shani/Developments/Projects/Luminus-publishers/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/shani/Developments/Projects/Luminus-publishers/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/shani/Developments/Projects/Luminus-publishers/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/shani/Developments/Projects/Luminus-publishers/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/shani/Developments/Projects/Luminus-publishers/plugins/**/*.{js,ts,mjs}","/home/shani/Developments/Projects/Luminus-publishers/composables/**/*.{js,ts,mjs}","/home/shani/Developments/Projects/Luminus-publishers/utils/**/*.{js,ts,mjs}","/home/shani/Developments/Projects/Luminus-publishers/pages/index.vue","/home/shani/Developments/Projects/Luminus-publishers/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/shani/Developments/Projects/Luminus-publishers/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/shani/Developments/Projects/Luminus-publishers/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;